spring:
  application:
    name: news
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time-zone: Asia/Kathmandu
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
server:
  port: ${PORT:8080}
  servlet:
    context-path: '/news/'
logging:
  level:
    org:
      springframework:
        security: DEBUG
external:
  news-api:
    key: ${NEWS_API_KEY}
    url: ${NEWS_API_URL}
internal:
  admin:
    user: ${ADMIN_USER}
    pass: ${ADMIN_PASS}